### ISSUE TITLE
A Couple requests (sorry didnt know whereelse to post this)

### ISSUE THREAD

**Issue by BarGuy** [knrd1/chatgpt#16]
Was wondering if you could add a feature that if a response is longer  that X amount of information, that it will post up to that and then include a pastebin link for the entire response

Also, anyway of incorporating something like Dan 9.0 or simiar into the script so the bot can be adjusted to more creative or non politically correct responses?

Thanks.. FYI, love the script

**Comment by knrd1** [comment]
Thanks for your message, asnwering the questions:

1) Maybe in the future I will add an option and a variable in chat.conf which will enable pastebin support, as you wish.

2) Great question! Currently ChatGPT IRC Bot only supports one object for a role (either "system", "user", or "assistant". It's "user" by default in chat,conf). My idea is to add support for all three, so for the role "system" you will be able to specify your own prompt in the config like Dan 9.0 or whaytever, more details of what you can do with all three roles: https://platform.openai.com/docs/guides/chat.

For the time being, if you care for answers which are not politically correct, I strongly encourage you to use the model "text-davinci-003" instead of the default "gtp-3.5-turbo". Model gtp-3.5-turbo is optimised for conversations, therefore quite heavily moderated and very polite. The text-davinci-003 model, on the other hand, does not use endpoint chat/completions. This model is not politically correct and will tell you literally anything you want. And it is still as capable as the gtp-3.5-turbo.
